---
# Kernel (genkernel) config
# https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Kernel

- name: Emerge Gentoo sources
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge gentoo-sources'
  args:
    creates: /mnt/gentoo/usr/src/linux/arch

- name: Select gnome/systemd profile
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; eselect profile set default/linux/amd64/17.1/'

# Ignore errors here because it has an expected return code of 1
# TODO: Not really sure how to write this as idempotent, as it writes out a file to an unpredictable temp location.
- name: Accept the license for linux-firmware if it doesn't exist (relies on CONFIG_PROTECT_MASK in make.conf)
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge sys-kernel/genkernel --autounmask-write'
  ignore_errors: true

# This step takes the temp unpredictable file from the previous step and writes it out to the more permanent config location.
- name: Accept the license for linux-firmware if it doesn't exist (relies on CONFIG_PROTECT_MASK in make.conf)
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; etc-update --automode -5'
  args:
    creates: /mnt/gentoo/etc/portage/package.license

- name: Emerge genkernel (does not build it yet)
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge sys-kernel/genkernel'
  args:
    creates: /mnt/gentoo/usr/bin/genkernel

#  It was implied that this is needed for systemd
# - name: Emerge dracut
#   command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge sys-kernel/dracut'

#  So this seems to be necessary to use systemd on LVM(?)
#  https://wiki.gentoo.org/wiki/Systemd
# - name: Emerge genkernel-next
#   command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge sys-kernel/genkernel-next'

#  Is this needed if we're not following the guide on systemd-boot?
# - name: Copy genkernel config
#   copy:
#     src: genkernel.conf
#     dest: /mnt/gentoo/etc/genkernel.conf

# Build our kernel
- name: Build genkernel
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; genkernel all'

# Builds only initramfs (not an entire kernel) with LVM support
- name: Install initramfs
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; genkernel --lvm --install initramfs'

- name: Write state file to show this task has completed
  file:
    path: /tmp/kernel_built
    state: touch
...
